version: '3.7'

services:
  zookeeper:
    image: zookeeper:3.5
    ports:
      - 2181:2181
    networks:
      - kafka_network
    volumes:
      - zookeeper_data:/data
      - zookeeper_datalog:/datalog
  kafka:
    image: kafka-custom
    ports:
      - 9092:9092
    networks:
      - kafka_network
    volumes:
      - kafka_data:/data
    environment:
      - ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
volumes:
  zookeeper_data:
    external: true
  zookeeper_datalog:
    external: true
  kafka_data:
    external: true
networks:
  kafka_network:
    external: true